sudo: required

language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

services:
  - mongodb

    
before_install:
- openssl aes-256-cbc -K $encrypted_d3b86bb7324d_key -iv $encrypted_d3b86bb7324d_iv -in super_secret.json.enc -out super_secret.json -d

install:
- pecl install mongodb || phpenv config-add testing/mongodb.ini;

before_script:
- mkdir -p build/logs
- ./cloud_sql_proxy -instances=$MYSQL_CONNECTION_NAME=tcp:3307 &
- ./cloud_sql_proxy -instances=$POSTGRES_CONNECTION_NAME=tcp:5433 &

script:
- chmod +x testing/run_test_suite.sh

after_success:
- chmod +x testing/run_coveralls.sh

after_script:
- chmod +x testing/test_cleanup.sh

deploy:
  provider: gae
  keyfile: super_secret.json
  project: web-app-jg
  config: app.yaml
